// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RelayPulse.Api.Data;

#nullable disable

namespace RelayPulse.Api.Data.Migrations
{
    [DbContext(typeof(RelayDbContext))]
    partial class RelayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RelayPulse.Api.Data.Account", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("industry");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("timezone");

                    b.HasKey("Id");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("RelayPulse.Api.Data.ActivityEvent", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("event_type");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("location");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Outcome")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("outcome");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "OccurredAt")
                        .HasDatabaseName("ix_activity_events_account_occurred");

                    b.ToTable("activity_events", (string)null);
                });

            modelBuilder.Entity("RelayPulse.Core.Time.WeekBucket", b =>
                {
                    b.Property<string>("Timezone")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("timezone");

                    b.Property<DateOnly>("WeekStartLocal")
                        .HasColumnType("date")
                        .HasColumnName("week_start_local");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit")
                        .HasColumnName("is_complete");

                    b.Property<DateTime>("UtcEnd")
                        .HasColumnType("datetime2")
                        .HasColumnName("utc_end");

                    b.Property<DateTime>("UtcStart")
                        .HasColumnType("datetime2")
                        .HasColumnName("utc_start");

                    b.HasKey("Timezone", "WeekStartLocal");

                    b.HasIndex("Timezone", "UtcStart")
                        .IsUnique()
                        .HasDatabaseName("ix_week_buckets_timezone_utc_start");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Timezone", "UtcStart"), new[] { "UtcEnd", "WeekStartLocal", "IsComplete" });

                    b.ToTable("week_buckets", (string)null);
                });

            modelBuilder.Entity("RelayPulse.Api.Data.ActivityEvent", b =>
                {
                    b.HasOne("RelayPulse.Api.Data.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
